#!/bin/bash

set -e

on_exit() {
    if [[ $? != 0 ]]; then
        printf "setup failed\n" >&2
    else
        printf "setup complete\n"
    fi
}
trap on_exit EXIT

EXIT_FAILURE=1
if [[ -n $ZSH_VERSION ]]; then
    SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)")"
elif [[ -n $BASH_VERSION ]]; then
    SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
else
    echo "Unsupported shell" >&2
    exit $EXIT_FAILURE
fi

(${SCRIPT_DIR}/bin/bootstrap.sh)

test -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" &&
    source "${HOME}/.nix-profile/etc/profile.d/nix.sh"

(fish "${SCRIPT_DIR}/bin/install.fish")

(fish "${SCRIPT_DIR}/bin/configure.fish")

exec "$SHELL"
