source ~/Dotfiles/nvim/plugins/airline.vim
source ~/Dotfiles/nvim/plugins/barbar.vim
source ~/Dotfiles/nvim/plugins/blamer.vim
source ~/Dotfiles/nvim/plugins/coc.vim
source ~/Dotfiles/nvim/plugins/dashboard.vim
source ~/Dotfiles/nvim/plugins/telescope.vim
source ~/Dotfiles/nvim/plugins/theme.vim
source ~/Dotfiles/nvim/plugins/vim-bbye.vim
source ~/Dotfiles/nvim/plugins/vim-rooter.vim
source ~/Dotfiles/nvim/plugins/which-key.vim
